export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_MORE_OPTIONS = 'TOGGLE_MORE_OPTIONS'
export const UPDATE_HEADER = 'UPDATE_HEADER'
export const GET_SONG = 'GET_SONG'
export const MOVE_TO_NEXT_CHORD = 'MOVE_TO_NEXT_CHORD'

export const YT_PLAYER_STATUS_CHANGED = 'YT_PLAYER_STATUS_CHANGED'