export const TOGGLE_MENU = 'TOGGLE_MENU'
export const SET_TRANSPOSE = 'SET_TRANSPOSE'
export const GET_SONG = 'GET_SONG'
export const MOVE_CHORD_TO = 'MOVE_CHORD_TO'

export const MOUNT_YT_PLAYER = 'MOUNT_YT_PLAYER'
export const UNMOUNT_YT_PLAYER = 'UNMOUNT_YT_PLAYER'
export const YT_PLAYER_STATUS_CHANGED = 'YT_PLAYER_STATUS_CHANGED'